CREATE   PROCEDURE Book.SP_Work_Create
AS

IF OBJECT_ID('Book.Work') IS NULL 

CREATE TABLE Book.Work (
  WorkID int NOT NULL IDENTITY,
  WorkName nvarchar(50) NULL,
  CONSTRAINT PK_Work PRIMARY KEY (WorkID)
);

RETURN;
